# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2021 Intel Corporation

FROM golang:1.17 AS allbuild

RUN apt-get update && apt-get install -y \
    make \
    clang \
    llvm \
    libbpf-dev \
    bpftool


ENV GO111MODULE=on
ENV GOPROXY=https://goproxy.cn,direct
RUN printenv|grep GOPROXY
